// <auto-generated />
using Biblioteca_Monzon_Randisi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca_Monzon_Randisi.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    partial class BibliotecaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.EstadoPrestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EstadosPrestamo");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.EstadoReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EstadosReserva");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GeneroId");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.Libro", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CantCopias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ISBN");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.LibrosGeneros", b =>
                {
                    b.Property<string>("LibroId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GeneroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LibroId", "GeneroId");

                    b.HasIndex("GeneroId");

                    b.ToTable("LibrosGeneros");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.Multa", b =>
                {
                    b.Property<int>("SocioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("SocioId");

                    b.ToTable("Multas");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.Prestamo", b =>
                {
                    b.Property<int>("SocioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibroId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FechaDevolucion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaPrestamo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaVencimiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SocioId", "LibroId");

                    b.HasIndex("Estado");

                    b.HasIndex("LibroId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.Reserva", b =>
                {
                    b.Property<int>("SocioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibroId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FechaReserva")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SocioId", "LibroId");

                    b.HasIndex("Estado");

                    b.HasIndex("LibroId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.Socio", b =>
                {
                    b.Property<int>("NroSocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoSocio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoSocioNavigationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NroSocio");

                    b.HasIndex("TipoSocioNavigationId");

                    b.ToTable("Socios");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.TipoSocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasPrestamo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLibrosSimutaneos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MultaPorDia")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TiposSocios");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.LibrosGeneros", b =>
                {
                    b.HasOne("Biblioteca_Monzon_Randisi.Models.Genero", "Genero")
                        .WithMany("LibrosGeneros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca_Monzon_Randisi.Models.Libro", "Libro")
                        .WithMany("LibrosGeneros")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.Multa", b =>
                {
                    b.HasOne("Biblioteca_Monzon_Randisi.Models.Socio", "Socio")
                        .WithOne("Multa")
                        .HasForeignKey("Biblioteca_Monzon_Randisi.Models.Multa", "SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.Prestamo", b =>
                {
                    b.HasOne("Biblioteca_Monzon_Randisi.Models.EstadoPrestamo", "EstadoNavigation")
                        .WithMany("Prestamos")
                        .HasForeignKey("Estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca_Monzon_Randisi.Models.Libro", "Libro")
                        .WithMany("Prestamos")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca_Monzon_Randisi.Models.Socio", "Socio")
                        .WithMany("Prestamos")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoNavigation");

                    b.Navigation("Libro");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.Reserva", b =>
                {
                    b.HasOne("Biblioteca_Monzon_Randisi.Models.EstadoReserva", "EstadoNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("Estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca_Monzon_Randisi.Models.Libro", "Libro")
                        .WithMany("Reservas")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca_Monzon_Randisi.Models.Socio", "Socio")
                        .WithMany("Reservas")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoNavigation");

                    b.Navigation("Libro");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.Socio", b =>
                {
                    b.HasOne("Biblioteca_Monzon_Randisi.Models.TipoSocio", "TipoSocioNavigation")
                        .WithMany("Socios")
                        .HasForeignKey("TipoSocioNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoSocioNavigation");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.EstadoPrestamo", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.EstadoReserva", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.Genero", b =>
                {
                    b.Navigation("LibrosGeneros");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.Libro", b =>
                {
                    b.Navigation("LibrosGeneros");

                    b.Navigation("Prestamos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.Socio", b =>
                {
                    b.Navigation("Multa");

                    b.Navigation("Prestamos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Biblioteca_Monzon_Randisi.Models.TipoSocio", b =>
                {
                    b.Navigation("Socios");
                });
#pragma warning restore 612, 618
        }
    }
}
